- name: Print debug message
  debug:
    msg:
      - "OS: {{ ansible_distribution }}"
      - "IP: {{ ansible_host }}"

- name: Set authorized key
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ ssh_public_key }}"
